databases:
  - name: postgres
    ipAllowList: []
    `databaseName`: Exchange_Forum_Db
    user: ryanongwx

services:
  - type: web
    name: exchange_forum_rails_backend
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false